### ISSUE TITLE
MK42 heatbed on Einsy board with 12v e3d and filament sensor and Pinda 2 probe

### ISSUE THREAD

**Issue by darkdelphi** [3d-gussner/Prusa-Firmware#49]
Ok so what I am looking for is how to change the Mk3 firmware to accomadate a 12v power supply and the mk42 heatbed but make use of the original pinda 2 probe and the prusa filament sensor. 
I have an original Einsy board from Ultimachine and an original E3D V6 12v. I also got the original bondtech   gears and have completely assembled a clone hotend (made certain to use black filament) 

Goal is eventually upgrade to full MK3 once the spring steel sheets are available for immediate purchase. I don't preorder as a rule.

**Comment by 3d-gussner** [comment]
@darkdelphi Hi,
So you want a kind of MK3 (no MK52 heated bed) but with 12V instead of 24V, right?
- You can run the EINSY from 12v to 24V https://ultimachine.com/products/einsy-rambo-1-1?variant=5522483773470 so no issues here.

- The Prusa MK2/s MK42 heated is 12V.

- As the EINSY has 5V for fans you cannot reuse the MK2 12V fans, you need the Noctua 5 V and 5050 part cooling fan with 5V ideal with the rpm sensor.

- I am pretty sure you need to change the TMC2130_current and/or DEFAULT_PWM_MOTOR_CURRENT for the TMC 2130 drivers in the firmware to get the same torque as with 24V. How much i cannot tell you. You also may need to check total current this setting will draw from your PSU and see if it is sufficient. 

- Also the MK2 height is different from the MK3, assuming you want to upgrade your MK2/s, so you need to change Z_MAX_POS from MK3 '210' to MK2 '200'
You may also check the X_MAX_POS and Y_MIN_POS values.

- PID settings for hotend and heated bed need to be adjusted

- The MK3 MK52 heated bed has 4 calibration points and the MK2 MK42 heated bed has 9 calibration points, so here you also need to take care of it. I am not sure if these points moved or not.

- Also is the PINDA position of the MK3 extruder is different compared to the MK2/s extruder and it may have issues to find the MK42 cal points if the y-axis is not moved. MK3 has Y_PROBE_OFFSET_FROM_EXTRUDER '5' and MK2 has a value of '9'...so it can be that you have to move the Z frame by 4mm

Hope that helps. I may forgot few things...if i can think of something else i will let you know.

**Comment by darkdelphi** [comment]
The fans I didn't even consider so that you very much, I just got those ordered and will have them tomorrow. If I were to go ahead and use 24v power supply where would could I still use the 12v extruder and bed, if it is simply a matter of changing the PID settings where are those located. or would it be simpler to turn on the einsy features on the mk2.5 12v variant of the firmware.

**Comment by 3d-gussner** [comment]
@darkdelphi You should not run a 12V heater cartridge or 12V MK42 bed on 24V, they can (probably will) fail.

- Changing the PID you should do on all printers as every is bit different, BUT it will not help you if you go for 24V PSU with 12V heater cartridge and 12V heated bed.

- Changing the heater cartridge to an 24V isn't a problem https://e3d-online.com/heater-cartidge-40w or you could ask prusa to get one.

- The MK42 bed is 12V and could be used with a 24V to 12V step down converter, but this would need a big one which could handle the needed current. At the end a MK52 bed could be cheaper.

As you have most parts now adding the 24V 40W heater cartidge + 24V MK52 bed + spring sheet and a 24V PSU this may be cost inefficient. It had been 'cheaper' to get the MK3 Upgrade kit.

The MK25 firmware is made for the miniRAMBO with an MK52 12V bed and not for the EINSY with MK42 bed. You could get some settings from that.
At the end you gonna need your own firmware with EINSY 12V + 12V E3dv6 + MK42 12V bed.

Sorry, it isn't that easy.

I ordered the MK3 Upgrade kit, 'GT-16 pulleys' and '623h Bearing with housing' from Prusa. Get some other parts like motors, rods, bearings, LCD, GT2 belt and fasteners from other sources and build a custom MK3 printer.
But my firmware changes will be much smaller than yours and so easier to maintain.

I love my MK2 with the miniRambo and think it has too much value in parts to switch everything, so i change few things on that one:
- Got a 12V noctua fan from Amazon and will connect it to the miniRAMbo (it is supported in the MK25 firmware
- Ordered the PINDAv2 which will also be connected to the miniRAMbo (MK25 firmware)
- Should get a spare bondtech gear out of the ordered MMU kit (MK25 firmware) that may change as the MMU v2.0 is coming and i have to order one extra.
- Should get a spare filament sensor out of the MMU upgrade kit MK2/MK25 to MK3 (MK25 firmware)
that may change as the MMU v2.0 is coming and i have to order one extra.
- I can use the MK2 firmware code settings for the MK42 bed i am using.
- As soon the powder coated spring steel sheets are available i will order it and use it on my MK2.3 or as spare on the custom MK3.

My changes are very close to the Prusa firmware releases so the custom changes will be minimal:
- MK25 firmware + custom height + MK42 bed settings for my MK2.3
- MK3 firmware + custom height for my custom MK3

**Comment by 3d-gussner** [comment]
@darkdelphi
Also to get your printer as close as possible to the MK3 you gonna need a 12V power panic circuit, which isn't available to buy even in 24V. You can get the https://shop.prusa3d.com/en/mk3-printer-parts/207-mk3-PSU-24v-240w.html but then you are close to MK3 upgrade kit costs and need a 24V MK52 bed + spring steel sheet + 24V heater cartridge, etc.

Here more info about the https://github.com/prusa3d/MK3_Power_Panic

**Comment by 3d-gussner** [comment]
@darkdelphi How is it going with your project?

**Comment by darkdelphi** [comment]
Ok so I decided to go ahead and get the 24v MK52 heatbed after I found out that the spring steel sheet 
 being as prusa is now just shipping them with PEI sheets slapped on, the powder coating isn't  being offered at all at this time. and since this can easily cut on my CNC machine I saw no reason to not go ahead and get it . So now the only part I couldn't acquire is the power panic board. 
My plan is to just learn enough to go through the opensource of the firmware and just comment out the use of that function I also want to change the PWM 5v fan to use just a simple two pin. I have ordered the 3pin from prusa but I can't find a 3 pin 50mm 5v blower fan on Amazon so if I want to get the printer up and going this weekend I am going to have to find away around this. I am guessing it is a data cable for pwm. 
If I could find someone that knew what files handled these I could go directly to them and make t he changes quickly and be up and running today. But as I don't really know much about how this is structured I will have to go through all the files one by one until I find what I am looking for. 
At a glance the firmware looks very similar to Marlin, sharing many of the same features and code design. But no search I have garnered has been able to gleam this information.

**Comment by darkdelphi** [comment]
Oh I was able to get the 5v Noctua, a 24v e3dv6 , as well as an original  Prusa MK3 thermister as well as an appropriate 24v 240w power supply,

**Comment by 3d-gussner** [comment]
Sounds great. Good luck with your project

**Comment by 3d-gussner** [comment]
Did you read this ? https://shop.prusa3d.com/forum/original-prusa-i3-mk2-f23/einsy-rambo-on-mk2--t6137-s30.html#p74913

**Comment by 3d-gussner** [comment]
Hi @darkdelphi how is it going? Do you think this issue should still be open? If not please close it.

**Comment by 3d-gussner** [comment]
Close issue due no active interaction for long time.
